DROP TABLE IF EXISTS task_executors;
DROP TABLE IF EXISTS task_watchers;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS sprints;
DROP TABLE IF EXISTS board_columns;
DROP TABLE IF EXISTS boards;
DROP TYPE IF EXISTS task_status;